### ISSUE TITLE
Native Linux VST stupport

### ISSUE THREAD

**Issue by DDRBoxman** [obsproject/obs-vst#3]

**Comment by c3r1c3** [comment]
While no where near complete, the below has been added:
PR #17:
Added some default Linux paths for the VST stuff (need to add VSTXH variable in the cmake stuff as well).
Added filtering to show the Linux ".so" files

**Comment by c3r1c3** [comment]
Well at least I tried.

I think most of the code is good, I just couldn't get the Linux  GUI stuff to work, AFAICT. It *should* be straight-forward, but it's outside my current skill range. Sorry.

**Comment by c3r1c3** [comment]
Just collecting some examples for when this issue is picked back up:
https://github.com/Ardour/ardour/blob/master/gtk2_ardour/linux_vst_gui_support.cc (esp. towards the end of the file).
https://github.com/Ardour/ardour/blob/master/libs/ardour/linux_vst_support.cc
https://github.com/Ardour/ardour/blob/master/libs/ardour/lxvst_plugin.cc

**Comment by c3r1c3** [comment]
Just referencing this with a draft PR:
https://github.com/obsproject/obs-vst/pull/55

**Comment by RarogCmex** [comment]
What's about now?

**Comment by DDRBoxman** [comment]
Well, I setup Ubuntu 20.20 and the VST gui's show up. There is an extra window that shows up that probably just needs a quick fix. I bet that using newer QT just fixed it.

**Comment by DDRBoxman** [comment]
https://github.com/obsproject/obs-vst/pull/61

**Comment by DDRBoxman** [comment]
https://github.com/obsproject/obs-studio/commit/bfc2063b1ac984e92579472180636e13edbb5c00
